/*
Test generated by RoostGPT for test go-sample using AI Type Open Source AI and AI Model mistralai/Mixtral-8x7B-Instruct-v0.1


1. Test scenario: Empty slice
- Input: []int{}
*/

Test scenario: Empty slice
- Input: []int{}
-