/*
Test generated by RoostGPT for test go-sample using AI Type Open Source AI and AI Model mistralai/Mixtral-8x7B-Instruct-v0.1


1. Test with a maximum number of 10, to check if
*/

1. Test with a maximum number of 10, to check if