// Test generated by RoostGPT for test go-unit-algo-string using AI Type Open AI and AI Model gpt-4

package LevenshteinDistance

import (
	"testing"
)

func TestLevenshteinDistance_c58c51e350(t *testing.T) {
	// Test case 1: Both strings are empty
	result := levenshteinDistance("", "")
	if result != 0 {
		t.Errorf("Expected 0, but got %d", result)
	}

	// Test case 2: One string is empty, the other is not
	result = levenshteinDistance("", "test")
	if result != 4 {
		t.Errorf("Expected 4, but got %d", result)
	}

	// Test case 3: Both strings are the same
	result = levenshteinDistance("test", "test")
	if result != 0 {
		t.Errorf("Expected 0, but got %d", result)
	}

	// Test case 4: Both strings are different
	result = levenshteinDistance("test", "tent")
	if result != 1 {
		t.Errorf("Expected 1, but got %d", result)
	}

	// Test case 5: Test with longer strings
	result = levenshteinDistance("kitten", "sitting")
	if result != 3 {
		t.Errorf("Expected 3, but got %d", result)
	}
}
