// Test generated by RoostGPT for test go-unit-algo-string using AI Type Open AI and AI Model gpt-4

package LevenshteinDistance

import (
	"testing"
)

func TestMin_296d0913dd(t *testing.T) {
	type args struct {
		a uint16
		b uint16
	}
	tests := []struct {
		name string
		args args
		want uint16
	}{
		{
			name: "Test case 1: a is less than b",
			args: args{a: 10, b: 20},
			want: 10,
		},
		{
			name: "Test case 2: a is greater than b",
			args: args{a: 30, b: 20},
			want: 20,
		},
		{
			name: "Test case 3: a equals b",
			args: args{a: 15, b: 15},
			want: 15,
		},
		{
			name: "Test case 4: a and b are zero",
			args: args{a: 0, b: 0},
			want: 0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := min(tt.args.a, tt.args.b); got != tt.want {
				t.Errorf("min() = %v, want %v", got, tt.want)
			}
		})
	}
}
