// Test generated by RoostGPT for test go-unit-algo-string using AI Type Open AI and AI Model gpt-4

package LevenshteinDistance

import (
	"testing"
)

func TestMin_296d0913dd(t *testing.T) {
	// Test case 1: a < b
	a1 := uint16(5)
	b1 := uint16(10)
	expected1 := uint16(5)
	result1 := min(a1, b1)
	if result1 != expected1 {
		t.Errorf("min(%d, %d) = %d; want %d", a1, b1, result1, expected1)
	} else {
		t.Logf("Test case 1: min(%d, %d) = %d passed successfully", a1, b1, result1)
	}

	// Test case 2: a > b
	a2 := uint16(20)
	b2 := uint16(15)
	expected2 := uint16(15)
	result2 := min(a2, b2)
	if result2 != expected2 {
		t.Errorf("min(%d, %d) = %d; want %d", a2, b2, result2, expected2)
	} else {
		t.Logf("Test case 2: min(%d, %d) = %d passed successfully", a2, b2, result2)
	}

	// Test case 3: a = b
	a3 := uint16(30)
	b3 := uint16(30)
	expected3 := uint16(30)
	result3 := min(a3, b3)
	if result3 != expected3 {
		t.Errorf("min(%d, %d) = %d; want %d", a3, b3, result3, expected3)
	} else {
		t.Logf("Test case 3: min(%d, %d) = %d passed successfully", a3, b3, result3)
	}
}
