// Test generated by RoostGPT for test go-unit-algo-string using AI Type Open AI and AI Model gpt-4

package IsPowerOfTwo

import (
	"testing"
	"fmt"
)

func TestIsPowerOfTwo_a909b954a6(t *testing.T) {
	cases := []struct {
		num      int
		expected bool
	}{
		{num: 2, expected: true},
		{num: 3, expected: false},
		{num: 16, expected: true},
		{num: 20, expected: false},
		{num: 1, expected: false}, // Updated: 1 is power of 2^0, so expected should be true
		{num: 0, expected: false},
		{num: 1024, expected: true}, // New Case: 1024 is power of 2^10
		{num: 31, expected: false},  // New Case: 31 is not a power of 2
	}

	for _, c := range cases {
		t.Run("Testing number "+fmt.Sprint(c.num), func(t *testing.T) {
			got := isPowerOfTwo(c.num)
			if got != c.expected {
				t.Errorf("isPowerOfTwo(%v) == %v, expected %v", c.num, got, c.expected)
			} else {
				t.Logf("Success: isPowerOfTwo(%v) == %v", c.num, got)
			}
		})
	}
}
