/*
Test generated by RoostGPT for test go-sample using AI Type Open Source AI and AI Model mistralai/Mixtral-8x7B-Instruct-v0.1

Sure, here are some test scenarios for the `isPowerOfTwo` function
*/

Test Scenarios:
1. Test with input 1, expected