/*
Test generated by RoostGPT for test go-sample using AI Type Open Source AI and AI Model mistralai/Mixtral-8x7B-Instruct-v0.1


Test Scenario 1: Testing for a successful search
- Input
*/

arr := []int{1, 2, 3, 4