/*
Test generated by RoostGPT for test go-sample using AI Type Open Source AI and AI Model mistralai/Mixtral-8x7B-Instruct-v0.1

 Sure, I'd be happy to help you come up with test scenarios for
*/

1. Testing the function with positive numbers
2. Testing the