// Test generated by RoostGPT for test go-unit-algo-string using AI Type Open AI and AI Model gpt-4

package HammingDistance

import (
	"log"
	"testing"
)

func TestHammingDistance_f17e8d7bc0(t *testing.T) {
	// Test case 1: Strings of equal length
	a1, b1 := "test", "tent"
	expected1 := 1
	result1 := hammingDistance(a1, b1)
	if result1 != expected1 {
		t.Error("Test Case 1 Failed: {a1: ", a1, ", b1: ", b1, "} expected: ", expected1, " got: ", result1)
	} else {
		t.Log("Test Case 1 Passed: {a1: ", a1, ", b1: ", b1, "} expected: ", expected1, " got: ", result1)
	}

	// Test case 2: Strings of different length
	a2, b2 := "test", "testing"
	defer func() {
		if r := recover(); r == nil {
			t.Error("Test Case 2 Failed: {a2: ", a2, ", b2: ", b2, "} expected panic but got nil")
		} else {
			t.Log("Test Case 2 Passed: {a2: ", a2, ", b2: ", b2, "} expected panic and got panic")
		}
	}()
	hammingDistance(a2, b2)
}
